/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jenkins.weavedreamer;

import com.jenkins.weavedreamer.models.EditingSession;
import com.jenkins.weavedreamer.print.AbstractWeaveDreamerPrintable;
import com.jenkins.weavedreamer.print.PrintPattern;
import com.jenkins.weavedreamer.print.PrintPickingList;
import com.jenkins.weavedreamer.print.PrintThreadingList;
import com.jenkins.weavedreamer.print.PrintTieup;
import com.jenkins.weavedreamer.print.PrintUIWindow;
import java.awt.event.WindowEvent;
import java.awt.print.PrinterJob;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author David
 */
public class WeaveDreamerPrintSelect extends java.awt.Dialog {

    /**
     * Creates new form WeaveDreamerPrintSelect
     */
    public WeaveDreamerPrintSelect(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // do the selection action
        jRadioButtonPrintPatternActionPerformed(new java.awt.event.ActionEvent("", 0, ""));
        //PrintFormatter = PrintPickingList.class;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtonPrint = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonPrintThreading = new javax.swing.JRadioButton();
        jRadioButtonPrintDraft = new javax.swing.JRadioButton();
        jRadioButtonPrintTieup = new javax.swing.JRadioButton();
        jRadioButtonPrintPicking = new javax.swing.JRadioButton();
        jRadioButtonPrintPattern = new javax.swing.JRadioButton();

        setBackground(java.awt.SystemColor.control);
        setLocation(new java.awt.Point(100, 100));
        setLocationRelativeTo(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jButtonPrint.setText("Print");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Print Selection"));

        buttonGroup1.add(jRadioButtonPrintThreading);
        jRadioButtonPrintThreading.setText("Threading");
        jRadioButtonPrintThreading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPrintThreadingActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonPrintDraft);
        jRadioButtonPrintDraft.setText("Draft");
        jRadioButtonPrintDraft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPrintDraftActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonPrintTieup);
        jRadioButtonPrintTieup.setText("TieUp");
        jRadioButtonPrintTieup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPrintTieupActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonPrintPicking);
        jRadioButtonPrintPicking.setText("Picking");
        jRadioButtonPrintPicking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPrintPickingActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonPrintPattern);
        jRadioButtonPrintPattern.setSelected(true);
        jRadioButtonPrintPattern.setText("Pattern");
        jRadioButtonPrintPattern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPrintPatternActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonPrintPattern, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButtonPrintDraft, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jRadioButtonPrintPicking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonPrintThreading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonPrintTieup, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jRadioButtonPrintPattern)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonPrintDraft)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonPrintThreading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonPrintPicking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonPrintTieup))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jRadioButtonPrintPattern, jRadioButtonPrintPicking, jRadioButtonPrintThreading, jRadioButtonPrintTieup});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButtonPrint)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrint)
                    .addComponent(jButtonCancel))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jRadioButtonPrintTieupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPrintTieupActionPerformed
        // TODO add your handling code here:
        PrintFormatter = PrintTieup.class;

    }//GEN-LAST:event_jRadioButtonPrintTieupActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
        AbstractWeaveDreamerPrintable pf2 = null;
        //jButtonPrint.setEnabled(false);

        try {
            //try{
            Constructor ct;
            ct = PrintFormatter.getDeclaredConstructor(session.getClass(), draftWindow.getClass());
            pf2 = (AbstractWeaveDreamerPrintable) ct.newInstance(session, draftWindow);
        } catch (NoSuchMethodException | SecurityException ex) {
            //Logger.getLogger(WeaveDreamerPrintSelect.class.getName()).log(Level.SEVERE, null, ex);
        } //Logger.getLogger(WeaveDreamerPrintSelect.class.getName()).log(Level.SEVERE, null, ex);
        catch (InstantiationException | IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
            Logger.getLogger(WeaveDreamerPrintSelect.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.setVisible(false);

        try {
            if (job.printDialog() && pf2 != null) {
                job.setPrintable(pf2);
                job.print();
            }
        } catch (Exception e) {
            /* handle exception */
        } finally {
            //jButtonPrint.setEnabled(true);
            this.setVisible(true);
        }

        // I think is better to leave selector open so user can print more
        //this.setVisible(false);
        //this.dispose();

    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jRadioButtonPrintPatternActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPrintPatternActionPerformed
        // TODO add your handling code here:
        PrintFormatter = PrintPattern.class;

    }//GEN-LAST:event_jRadioButtonPrintPatternActionPerformed

    private void jRadioButtonPrintPickingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPrintPickingActionPerformed
        // TODO add your handling code here:
        PrintFormatter = PrintPickingList.class;


    }//GEN-LAST:event_jRadioButtonPrintPickingActionPerformed

    private void jRadioButtonPrintThreadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPrintThreadingActionPerformed
        // TODO add your handling code here:
        PrintFormatter = PrintThreadingList.class;
    }//GEN-LAST:event_jRadioButtonPrintThreadingActionPerformed

    private void jRadioButtonPrintDraftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPrintDraftActionPerformed
        // TODO add your handling code here:
        PrintFormatter = PrintUIWindow.class;
    }//GEN-LAST:event_jRadioButtonPrintDraftActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WeaveDreamerPrintSelect dialog = new WeaveDreamerPrintSelect(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        }
        );
    }

    public int PrintWeavingDraft(EditingSession session, WeavingDraftWindow draftWindow) {

        this.session = session;
        this.draftWindow = draftWindow;

        // show the form 
        this.setVisible(true);
        return 1;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonPrintDraft;
    private javax.swing.JRadioButton jRadioButtonPrintPattern;
    private javax.swing.JRadioButton jRadioButtonPrintPicking;
    private javax.swing.JRadioButton jRadioButtonPrintThreading;
    private javax.swing.JRadioButton jRadioButtonPrintTieup;
    // End of variables declaration//GEN-END:variables

    private EditingSession session;
    //private AbstractWeaveDreamerPrintable PrintFormatter; 
    private Class PrintFormatter;
    private WeavingDraftWindow draftWindow;
}
